mosip-compliance-toolkit/src/main/resources/application.properties
Reverts mosip/mosip-compliance-toolkit#15
=> Revert "Update application.properties"

db_scripts/mosip_toolkit/db.sql
=> corrected db name

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/controllers/SbiProjectController.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/SbiProjectService.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/util/DataValidationUtil.java
DataValidationUtil changes
SbiProjectService changes to take app.prop id from @value
=> MOSIP-21500

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/constants/SbiSpecVersions.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/constants/ToolkitErrorCodes.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/controllers/TestCasesController.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/dto/testcases/TestCaseDto.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/exceptions/ToolkitException.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/repository/TestCasesProjectRepository.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/SbiProjectService.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/TestCasesService.java, mosip-compliance-toolkit/src/main/resources/application.properties
a) getSbiTestCases
b) ToolkitException.. here io.mosip.kernel.core.exception.BaseUncheckedException should have constructor to override 
public ToolkitException(String errorCode, String errorMessage, Throwable rootCause) {
super(errorCode, errorMessage, rootCause);
}
should have 
public BaseUncheckedException (String errorMessage, Throwable rootCause) {
super(errorMessage, rootCause);
}
=> MOSIP-23194

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/controllers/CollectionsController.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/dto/CollectionDto.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/entity/CollectionSummaryEntity.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/entity/CollectionTestcaseKey.java
Reverts mosip/mosip-compliance-toolkit#78
=> Revert "MOSIP-23192 : runId added for getCollections"

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/SBIValidator.java
made inner class static for trust root validation
=> MOSIP-23198

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/controllers/TestRunController.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/repository/TestRunRepository.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/TestRunService.java
Reverts mosip/mosip-compliance-toolkit#109
=> Revert "MOSIP-23383 : pagination added"

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/repository/TestRunDetailsRepository.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/repository/TestRunRepository.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/TestRunService.java, mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/TestRunServiceTest.java
Reverts mosip/mosip-compliance-toolkit#140
=> Revert "MOSIP-23760 : get testRun Status considering all testcases in collection"

db_scripts/mosip_toolkit/ddl/sdk_projects.sql, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/controllers/SdkProjectController.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/dto/projects/SdkProjectDto.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/entity/SdkProjectEntity.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/SdkProjectService.java
Reverts mosip/mosip-compliance-toolkit#138
=> Revert "[MOSIP-23724] api services :put endpoint to update url and test data …"

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/controllers/TestCasesController.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/TestCasesService.java
Reverts mosip/mosip-compliance-toolkit#172
=> Revert "MOSIP-23689 : generate sdk request from object store"

mosip-compliance-toolkit/Dockerfile, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/BiometricTestDataService.java, mosip-compliance-toolkit/src/main/resources/application.properties
Reverts mosip/mosip-compliance-toolkit#209
=> Revert "Mosip 23936 add configurable option to perform virus scan on the zip file being uploaded in biometric test data screen"

.github/workflows/push_trigger.yml, mosip-compliance-toolkit/pom.xml
1. MOSIP-24556 bug fixes
2. MOSIP-24402 ResponseMisMatchValidator testcases
3. MOSIP-24061 Save hash of test data file & "testDataSource" in test run details 
4. MOSIP-24408 2 new SBI testcases added
5. MOSIP-24699 MatchMultiGalleryValidator added
6. Added "methodUrl" in test run details
=> Created 1.0.0-b2

.github/workflows/push_trigger.yml
Reverts mosip/mosip-compliance-toolkit#321
=> Revert "updated key"

.github/workflows/push_trigger.yml
Reverts mosip/mosip-compliance-toolkit#320
=> Revert "trying sonar analysis fix"

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/SbiProjectServiceTest.java, mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/TestCasesServiceTest.java, mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/TestRunServiceTest.java
Reverts mosip/mosip-compliance-toolkit#391
=> Revert "MOSIP-25370: Junit tests"

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/controllers/AndroidController.java
Reverts mosip/mosip-compliance-toolkit#435
=> Revert "added loggers"

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ResponseMismatchValidator.java
Updated for response mismatch validation description key
=> MOSIP 23010 - view test run 

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ResponseMismatchValidator.java
Response Mismatch validator description key
=> MOSIP 23010 - formatted java file

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/dto/testcases/ValidationResultDto.java
Removed results Map from validationResponseDto
=> MOSIP 23010 - Removed results Map

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ResponseMismatchValidator.java
updated success and failure messages in validationResultDto for ResponseMismatchValidator
=> MOSIP 23010 - view last test run

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/KeyRotationValidator.java
added description keys for key rotation validators
=> MOSIP 23010 - Key rotation validator

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/TimeCheckValidator.java
added description keys for time check validator
=> MOSIP 23010 - time check validator

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/QualityCheckValidator.java
added description keys for quality check validator
=> MOSIP 23010 - description keys for quality check validator

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/BiometricsQualityCheckValidator.java
added description keys for biometrics quality check validator
=> MOSIP 23010 - biometrics quality check validator

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ISOStandardsValidator.java
added description keys for ISO standards validator
=> MOSIP 23010 - ISO Validator

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/BiometricTestDataService.java
Add biometric test data for ABIS - service implementation
=> MOSIP-26931  Add biometric test data for ABIS - service implementation

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/BiometricTestDataService.java
=> MOSIP-26931 Code refactoring

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/BiometricTestDataService.java
=> MOSIP-26931 Abis test data upload

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/BiometricTestDataService.java
upload ABIS biometric test data for service
=> MOSIP-26931 upload ABIS biometric test data for service 

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/BiometricTestDataService.java
Download sample biometric test data for ABIS
=> MOSIP-26931 Download sample biometric test data for ABIS

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/BiometricTestDataService.java
download sample test data for ABIS
=> MOSIP-26931 download sample test data for ABIS

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/BiometricTestDataService.java, mosip-compliance-toolkit/src/main/resources/application.properties
=> MOSIP-26931 ABIS download sample file

db_upgrade_scripts/mosip_toolkit/sql/1.1.0_to_1.2.0-rollback.sql, db_upgrade_scripts/mosip_toolkit/sql/1.1.0_to_1.2.0-upgrade.sql
Reverts mosip/mosip-compliance-toolkit#555
=> Revert "Added purpose col"

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ExpectedFailureReasonValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/IdentifyDuplicateFoundValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/IdentifyDuplicateNotFoundValidator.java
multilanguage support for new validators and testcases
=> MOSIP-27656 multilanguage support for new validators and testcases

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ExpectedDuplicateCountValidator.java
multilanguage fixes for new validators
=> MOSIP-27656 multilanguage fixes for new validators

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/BiometricTestDataServiceTest.java
Sonar coverage for ABIS bio test data upload/download(sample)
=> MOSIP-26939 Sonar coverage for ABIS bio test data upload/download

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/BiometricTestDataService.java
Validate ROOT Folder and purpose folders for ABIS
=> MOSIP-26931 Validate ROOT Folder and purpose folders for ABIS

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/BiometricTestDataServiceTest.java
=> MOSIP-26939 Sonar coverage ABIS

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/BiometricTestDataService.java
=> MOSIP-26939 Sonar coverage for ABIS

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ConvertDataValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ConvertInvalidDataValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ConvertNoInputDataValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ExpectedDuplicateCountValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ExpectedFailureReasonValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ExtractTemplateInvalidDataValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ExtractTemplateNoInputDataValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ExtractTemplateValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ISOStandardsValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/IdentifyDuplicateFoundValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/IdentifyDuplicateNotFoundValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/KeyRotationValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/MatchInvalidDataValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/MatchMultiGalleryValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/MatchNoDataValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/MatchValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/QualityCheckInvalidDataValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/QualityCheckNoDataValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/QualityCheckValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ResponseMismatchValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/SBIValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/SegmentInvalidDataValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/SegmentNoInputDataValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/SegmentValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/SignatureValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/TimeCheckValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/TimeoutValidator.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/TransactionIdValidator.java
description key for exceptions
=> set description keys for validator exceptions

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/TestCasesServiceTest.java
=> ISO validator junit

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/QualityCheckValidator.java
Quality check message for multi modality
=> MOSIP-27940 Quality check message for multi modality

mosip-compliance-toolkit/pom.xml, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/BiometricTestDataService.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/ISOStandardsValidator.java
ISO validator multi language for image validation
=> MOSIP-25817 ISO validator

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/controllers/TestCasesController.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/TestCasesService.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/util/HashUtil.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/BioHashValidator.java
added BioHashValidator for validating hash content
=> MOSIP-26582 added BioHashValidator for validating hash content

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/TestCasesServiceTest.java
=> MOSIP-26582 testcase for hashvalidator

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/BioHashValidator.java
=> MOSIP-26582 stackTrace Error fix

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/util/HashUtil.java
=> MOSIP-26582 service error fix

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/BioHashValidator.java
=> MOSIP-26582 log error for debug

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/BioHashValidator.java, resources/compliance_test_definitions_abis.json
testdefinitions for ABIS3030 and ABIS3031
=> MOSIP-28130 testdefinitions for ABIS3030 and ABIS3031

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/controllers/ABISDataShareController.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/entity/AbisDataShareTokenEntity.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/entity/AbisDataShareTokenPK.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/repository/AbisDataShareTokenRepository.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/ABISDataShareService.java
save datashare token in toolkit db
=> MOSIP-28140 save datashare token in toolkit db

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/validators/HashValidator.java
updated success and failure messages for hash validator
=> updated success and failure messages for hash validator

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/controllers/ABISDataShareControllerTest.java, mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/ABISDataShareServiceTest.java
=> MOSIP-28140 saveDataShareToken testcases

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/controllers/ABISDataShareControllerTest.java, mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/ABISDataShareServiceTest.java
added test cases for invalidate datashare token
=> MOSIP-28140 added test cases for invalidate datashare token

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/SbiProjectService.java, mosip-compliance-toolkit/src/main/resources/application.properties
=> MOSIP-28448 Add default testcase SBI

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/AbisProjectService.java, mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/SdkProjectService.java
Add default testcase SDK and ABIS
=> MOSIP-28448 Add default testcase SDK and ABIS

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/AbisProjectServiceTest.java, mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/SbiProjectServiceTest.java, mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/SdkProjectServiceTest.java
junit for Add default testcase SBI,SDK and ABIS
=> MOSIP-28448 junit for Add default testcase SBI,SDK and ABIS

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/controllers/ReportGeneratorControllerTest.java, mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/ReportGeneratorServiceTest.java
=> MOSIP-28691 junit for report generator

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/SbiProjectServiceTest.java
=> MOSIP-28691 junit for SbiProjectService

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/controllers/SbiProjectControllerTest.java
junit for SbiProjectController
=> MOSIP-28691 junit for SbiProjectController

mosip-compliance-toolkit/src/main/java/io/mosip/compliance/toolkit/service/ReportGeneratorService.java, mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/ReportGeneratorServiceTest.java
junit coverage for report generator service
=> MOSIP-28691 junit coverage for report generator service

mosip-compliance-toolkit/src/test/java/io/mosip/compliance/toolkit/service/SbiProjectServiceTest.java
junit coverage for sbi project service
=> MOSIP-28691 junit coverage for sbi project service

mosip-compliance-toolkit/src/main/resources/application.properties
Reverts mosip/mosip-compliance-toolkit#889
=> Revert "MOSIP-24690 : updated properties for session idle logout"

helm/compliance-toolkit/install.sh, helm/compliance-toolkit/keycloak-init-values.yaml, helm/compliance-toolkit/keycloak-init.sh
* [MOSIP-30473] updated keycloak-init script to enable captcha
* [MOSIP-30473] fixed deployment issues
* [MOSIP-30473] fixed deployment issues
[MOSIP-30473]: https://mosip.atlassian.net/browse/MOSIP-30473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOSIP-30473]: https://mosip.atlassian.net/browse/MOSIP-30473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOSIP-30473]: https://mosip.atlassian.net/browse/MOSIP-30473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOSIP-30473] updated keycloak-init script to enable captcha (#934)
